### PR TITLE
[libcommhistory] Fix race when sending a temporary file with MMS. JB#56314

### PR DESCRIPTION
**Pull request by pvuorela**
If the file to be sent is a temporary file, the owner might assume
it can be removed after sendMessage() finishes. Avoid that by
creating a temporary file owned by the helper, hard link as first
option and file copy if that fails.

The copy case might not be the most efficient, but the files should
be small enough here and it's simple on api.

@Tomin1 @monich

### CODE REVIEW

**Comment by monich** [comment]
Now that you're touching it, why not to use the opportunity to switch from `sendMessage` to [`sendMessageFd`](https://github.com/sailfishos/mms-engine/blob/master/mms-engine/org.nemomobile.MmsEngine.xml#L168) D-Bus call, like it's already done in [commhistory-daemon](https://github.com/sailfishos/commhistory-daemon/commit/c4309f1). That would be far more efficient.

**Comment by pvuorela** [comment]
Mentioned already a bit of rationale for this, but more thoroughly:
- It's simple
- Shared files should be here relatively small so expecting the real life benefit is not necessarily too big. Often the copying wouldn't be absolutely required either.
- Fd based sending would have required new api here and then using it on mms sender side. Not sure either of those file descriptors on qml.
- Unless the current sendMessage() attachment api is removed, this should be fixed anyway.

**Comment by monich** [comment]
AFAICT no new API is required, everything is already in place. You don't need to pass fds from QML, files can be opened (and then closed after submitting the D-Bus call) on the native side.

Fd-based method is not only more efficient, it's also more reliable. Once fds have been dup'ped, the original ones can be closed and files can be removed from the filesystem, there's no room for race condition. And I think image files are large enough to be worth the trouble. Although one may argue that the whole thing is already so inefficient that even a few megabytes here and there won't make any noticeable difference 😐️

**Comment by Tomin1** [comment]
I think the idea of needing a new API was coming from the fact that there is also some fd "magic" going on application side already and those fds could be passed directly from the app to libcommhistory if some new API was added. They would be passing through QML then. While I think fd passing might be slightly neater and perhaps a bit more efficient in some (rare?) cases, this seems to me like a good enough solution until we think a bit more about this fds + QML case. Although I could also see that if this used already fd passing it might make a future change to pass fds directly slightly simpler, maybe.

**Comment by pvuorela** [comment]
Yea, we were talking about bit different things. The sharing side passes an fd that has been opened with more privileges and in theory could be passed all the way here.

But indeed the mmshelper here could be switched from sendMessage to sendMessageFd which would open the files and add the fd to each sent item. I could investigate that a bit more, though the most important thing is fixing the race :)

**Comment by pvuorela** [comment]
Actually that would require new api, not in qml but in commhistoryd. Now the mms-engine / org.nemomobile.MmsEngine has sendMessageFd() but the calls from here go to commhistoryd / org.nemomobile.MmsHandler which has only sendMessage() and sendMessageEvent(). Think there should be a new variant that would write the content from the file descriptor into a file that can be used later to retry sending.

Leaning now a bit more towards just fixing the race first and handling that fd version as an optimization task.

**Comment by Tomin1** [comment]
> Leaning now a bit more towards just fixing the race first and handling that fd version as an optimization task.

I would be fine with this.

**Comment by monich** [comment]
> Leaning now a bit more towards just fixing the race first and handling that fd version as an optimization task.

fds would fix the race too, wouldn't they? And it's a chance to make an improvement here and now, optimization tasks very rarely get any attention. But it's your call, of course!

**Comment by pvuorela** [comment]
> fds would fix the race too, wouldn't they? And it's a chance to make an improvement here and now, optimization tasks very rarely get any attention. But it's your call, of course!

Having same kind of prioritization problem even without task to pick, lots of things need fixing :/ I added a TODO commit to note that such Fd version could be implemented. Also if fix is picked to branch think it's nice if the fix is touching less code now.

So if anyone just approves the PR I'd be happy to merge. The more efficient version task is free to take :)

**Review by Tomin1 — APPROVED** [review]

**Comment by Olf0** [comment]
Just for the reference: This race condition already [caused a real life issue](https://forum.sailfishos.org/t/bug-mms-doesnt-send-pictures-when-patchmanager-is-installed/9925/9), although it still needs to be fully researched how much Patchmanager contributes to this.

Becoming aware of the technical background of this interaction, which appeared to be very far-fetched at first sight, I rather see @monich's file-descriptor based approach being pursued:
While it does not appear to be much extra work, its design is inherently more robust (i.e., fail-safe; minus implementation flaws, as always :wink:).

**Pull request merged**
