### PR TITLE
[libcommhistory] Create a recipient from a phone number.

### PR DESCRIPTION
**Pull request by dcaliste**
Allow to create recipients from phone numbers, the ring account is then assumed.

### CODE REVIEW

**Review by pvuorela — APPROVED** [review]
Seems to work nice with the filter.

Spotting couple places with RING_ACCOUNT which could perhaps be migrated to the new method and get rid of some more cases of the special name and common utils. I'm ok with or without such.

**Comment by dcaliste** [comment]
> Spotting couple places with RING_ACCOUNT which could perhaps be migrated to the new method 

Indeed, that's also a good justification for the new API. I'll amend the commit. Thanks for the suggestion.

**Comment by pvuorela** [comment]
If you still change, do rebase please too.

**Comment by dcaliste** [comment]
I've rebased the PR. I've just spotted one place where Recipient(RING_ACCOUNT, ...) can be replaced by the new method.

**Comment by pvuorela** [comment]
For other place I was thinking declarative/src/declarativerecipienteventmodel.cpp - setRecipients(Recipient(RING_ACCOUNT, m_remoteUid));

**Comment by pvuorela** [comment]
Also tests having some cases with RING_ACCOUNT and phone number.

**Comment by dcaliste** [comment]
Ah, right, I grep only under `src/`. Let me change it in these places also.

**Comment by dcaliste** [comment]
I've also added a RecipientList::fromPhoneNumbers() to follow the same spirit. And changed places where it was called like RecipientList::fromUids(RING_ACCOUNT, ...).

**Comment by pvuorela** [comment]
Thanks, still looking good. Nicely brings the amount of RING_ACCOUNT instances a bit down.

**Pull request merged**
